event_access_unifi.settings:
  type: config_object
  label: 'Event Access UniFi settings'
  mapping:
    api_host:
      type: string
      label: 'UniFi Access API host'
    api_token:
      type: string
      label: 'UniFi Access API token'
    verify_ssl:
      type: boolean
      label: 'Verify SSL certificates'
    visitor_default_door_ids:
      type: sequence
      label: 'Default UniFi door IDs'
      sequence:
        type: string
    offset_before_start_minutes:
      type: integer
      label: 'Offset before start (minutes)'
    window_from_start_minutes:
      type: integer
      label: 'Window from start (minutes)'
    email_sender:
      type: string
      label: 'Override email sender'
    email_subject:
      type: label
      label: 'Email subject template'
    email_body:
      type: text
      label: 'Email body template'
